# @license 3-clause BSD
# @link https://github.com/FeedbackField/FeedbackField-Core

services:
    my.listener:
        class: FeedbackFieldBundle\EventListener\PrePersistEventListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    feedback_field_type_finder:
        class: FeedbackFieldBundle\FeedbackFieldTypeFinderService
        arguments: ["@service_container"]
    twig.StatsFiltersDatesExtension:
        class: FeedbackFieldBundle\Twig\StatsFiltersDatesExtension
        public: false
        tags:
            - { name: twig.extension }




