services:
    feedback_field_type_text.type:
        class: FeedbackFieldTypeTextBundle\FeedbackFieldTypeTextService
        arguments: ["@service_container"]
        tags:
          -  { name: feedback_field_type.definition }
